name: telegram-summarizer
region: nyc
services:
  - name: web
    github:
      repo: kamforo/telegram-summarizer
      branch: main
      deploy_on_push: true
    build_command: npm ci && npx prisma generate && npm run build
    run_command: npx prisma db push && npm start
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: DASHBOARD_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    http_port: 3000

databases:
  - name: db
    engine: PG
    production: true
